---
- name: install and start apache
  hosts: target
  vars_files: vars/vars.yml

  tasks:
  - name: httpd package is present
    yum:
      name: httpd
      state: latest

  - name: copy web.html
    copy:
      src: "{{ stage2 }}.html"
      dest: /var/www/html/index.html

  - name: httpd is started
    service:
      name: httpd
      state: started

  - name: check that a page returns a status 200 and fail if the word
    uri:
      url: http://10.184.0.21
      return_content: true
    register: this

  - name: debug
    debug:
      var: this
